services:
  - type: web
    name: intelliclaim-frontend
    env: static
    plan: starter
    region: oregon
    runtime: node
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://intelliclaim-project.onrender.com   # Update with your backend URL
    autoDeploy: true