services:
  - type: web
    name: intelliclaim-frontend
    env: static
    plan: starter
    region: oregon
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: @https://intelliclaim-project.onrender.com   # Update with your backend URL
    autoDeploy: true